#**Slice elements from index 1 to index 5 from the following array:**

In [6]:
import numpy as np

arr=np.array([0,1,2,4,5,6,7,8,9])
print (arr[1:5])

[1 2 4 5]


**Slice elements from index 4 to the end of the array:**

In [7]:
import numpy as np

arr=([1,3,4,5,6,7,8,9])
print(arr[4 :])#selects from the start index to the last

[6, 7, 8, 9]


**Slice elements from the beginning to index 4 (not included):**

In [11]:
arr=([1,2,4,7,2,9,7,0])
print(arr[:4])

[1, 2, 4, 7]


**Slice from the index 3 from the end to index 1 from the end:**

In [12]:
arr=([1,2,4,7,2,9,7,0])

#negative sliciing starts with -1 and -1 means the last index
print(arr[-3:-1])


[9, 7]


**STEP**
**Return every other element from index 1 to index 5:**

In [13]:
arr=([1,2,4,7,2,9,7,0])
#STARD:END:STEP

print(arr[1:5:2])



[2, 7]


**return every other element from the entire array:**

In [21]:
arr=np.array([1,2,4,7,2,9,7,0])
print(arr[::2])

[1 4 2 7]


**slice 789**

In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[1, 1:3])


[7 8]


**From both elements, return index 2: colum 3,8**

In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2,2])

[3 8]


**both rows and colums from the middle parts slice it**

In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


**specific elememts**

In [25]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0,2])
print(arr[1,3])

3
9


**get a specific row**

In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr[0])
print(arr[0,:])

print(arr[0:2,2])

[1 2 3 4 5]
[1 2 3 4 5]
[3 8]


**change number 9 to any number you want**

In [46]:
import numpy as np

arr = np.array([[1, 2, 4, 5,11],
                [6, 7, 8, 9, 10]])

arr[1,3]=23
print(arr)

#chnage the entire rows

arr[1]=5
print(arr)

arr[0:2,3]=999
print(arr)


arr[0,1:3]=[3,3]
print(arr)



[[ 1  2  4  5 11]
 [ 6  7  8 23 10]]
[[ 1  2  4  5 11]
 [ 5  5  5  5  5]]
[[  1   2   4 999  11]
 [  5   5   5 999   5]]
[[  1   3   3 999  11]
 [  5   5   5 999   5]]


**ALL 0s matrices**

In [57]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**all 1s matrices**

In [58]:
np.ones(1)

array([1.])

In [64]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

**any other numbers:**

*   it takes two paramters the shape and the value

In [63]:
np.full((2,2),123,dtype=float)

array([[123., 123.],
       [123., 123.]])

**random decimla numbers**

In [65]:
np.random.rand(4,4)

array([[0.90000942, 0.24055181, 0.48990256, 0.00579335],
       [0.82409981, 0.8319493 , 0.33398686, 0.77089569],
       [0.82933511, 0.25985638, 0.15984122, 0.79765359],
       [0.22750037, 0.92774383, 0.01919569, 0.28963536]])

In [73]:
np.random.randint(4,size=(3,4))
#if you dont specify the size its just gonna show 1 random numbers

array([[3, 0, 2, 2],
       [2, 2, 3, 0],
       [0, 3, 3, 0]])

In [75]:
#if you want a number between 3 to 8
np.random.randint(3,9,size=(3,4))
#9 is exclusive so itdoenot include 9

array([[5, 5, 3, 3],
       [8, 6, 7, 6],
       [7, 5, 6, 5]])

**identitity matrix**

1.   this only need one paramter because by nature its going to be sqaure matrix



In [78]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])